// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// 
///  import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyNIeOyZbbm1hsz-jl14mkYlF1v8Op9Bk',
    appId: '1:490715153732:web:54aaf2d2cb04f04f604311',
    messagingSenderId: '490715153732',
    projectId: 'fir-flutter-codelab-ee659',
    authDomain: 'fir-flutter-codelab-ee659.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ee659.appspot.com',
    measurementId: 'G-JV7JBBFWV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHT5msDgd0DSJ4ajcT3W1OrU4VG4cIToQ',
    appId: '1:490715153732:android:ba83b79e7ede19f4604311',
    messagingSenderId: '490715153732',
    projectId: 'fir-flutter-codelab-ee659',
    storageBucket: 'fir-flutter-codelab-ee659.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB9_hGb3go_nYoq_vGQS97IN12n4kN_2c',
    appId: '1:490715153732:ios:98a67c9ab21f646f604311',
    messagingSenderId: '490715153732',
    projectId: 'fir-flutter-codelab-ee659',
    storageBucket: 'fir-flutter-codelab-ee659.appspot.com',
    iosClientId: '490715153732-kjjen2d0v887k2m3g98sp3pgvnf12jfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupNamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB9_hGb3go_nYoq_vGQS97IN12n4kN_2c',
    appId: '1:490715153732:ios:98a67c9ab21f646f604311',
    messagingSenderId: '490715153732',
    projectId: 'fir-flutter-codelab-ee659',
    storageBucket: 'fir-flutter-codelab-ee659.appspot.com',
    iosClientId: '490715153732-kjjen2d0v887k2m3g98sp3pgvnf12jfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupNamer',
  );
}
